# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='cantidad_partos',
            field=models.IntegerField(default=0),
        ),
    ]
