# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0003_auto_20180821_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='fecha_aproximada_parto',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='fecha_aumento',
        ),
    ]
