# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produccion', '0003_auto_20180820_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_produccion',
            name='Animales',
        ),
    ]
