# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produccion', '0005_registro_produccion_animales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_produccion',
            old_name='fecha_produccion',
            new_name='fecha_de_produccion',
        ),
    ]
