# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0004_auto_20180821_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='cantidad_partos',
            new_name='cantidad_de_partos',
        ),
    ]
