# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0005_auto_20180821_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='estado',
            new_name='estado_del_animal',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='etapa',
            new_name='etapa_del_animal',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='fecha_nacimiento',
            new_name='fecha_de_nacimiento',
        ),
    ]
