# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reportes', '0002_auto_20180820_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportes',
            old_name='Listado_novillas',
            new_name='listado_novillas',
        ),
        migrations.RenameField(
            model_name='reportes',
            old_name='Listado_novillos',
            new_name='listado_novillos',
        ),
        migrations.RenameField(
            model_name='reportes',
            old_name='Listado_terneras',
            new_name='listado_terneras',
        ),
        migrations.RenameField(
            model_name='reportes',
            old_name='Listado_terneros',
            new_name='listado_terneros',
        ),
        migrations.RenameField(
            model_name='reportes',
            old_name='Listado_toros',
            new_name='listado_toros',
        ),
        migrations.RenameField(
            model_name='reportes',
            old_name='Listado_vacas_en_produccion',
            new_name='listado_vacas_en_produccion',
        ),
        migrations.RenameField(
            model_name='reportes',
            old_name='Listado_vacas_prenadas',
            new_name='listado_vacas_prenadas',
        ),
    ]
