# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0003_auto_20180821_1148'),
        ('Produccion', '0004_remove_registro_produccion_animales'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_produccion',
            name='Animales',
            field=models.ManyToManyField(to='Animal.Animal'),
        ),
    ]
