# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='Listado_novillas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportes',
            name='Listado_novillos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportes',
            name='Listado_terneras',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportes',
            name='Listado_terneros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportes',
            name='Listado_toros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportes',
            name='Listado_vacas_en_produccion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportes',
            name='Listado_vacas_prenadas',
            field=models.IntegerField(default=0),
        ),
    ]
