# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reportes', '0004_auto_20180821_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportes',
            old_name='listado_novillas',
            new_name='lista_de_novillas',
        ),
        migrations.RenameField(
            model_name='reportes',
            old_name='listado_novillos',
            new_name='lista_de_novillos',
        ),
        migrations.RenameField(
            model_name='reportes',
            old_name='listado_terneras',
            new_name='lista_de_terneras',
        ),
        migrations.RenameField(
            model_name='reportes',
            old_name='listado_terneros',
            new_name='lista_de_terneros',
        ),
        migrations.RenameField(
            model_name='reportes',
            old_name='listado_toros',
            new_name='lista_de_toros',
        ),
        migrations.RenameField(
            model_name='reportes',
            old_name='listado_vacas_en_produccion',
            new_name='lista_de_vacas_en_produccion',
        ),
        migrations.RenameField(
            model_name='reportes',
            old_name='listado_vacas_prenadas',
            new_name='lista_de_vacas_prenadas',
        ),
    ]
