# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reportes', '0005_auto_20180821_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportes',
            old_name='produccion_lactea_grupal',
            new_name='produccion_lactea_grupal_por',
        ),
    ]
